WITH RN AS (

	SELECT *, ROW_NUMBER () OVER (PARTITION BY USER_ID ORDER BY START_TIME DESC) AS RN FROM SESSION

),
	END_TIME_PREVIOUS_VISIT AS (

		SELECT USER_ID, START_TIME, END_TIME, RN,
		LAG(START_TIME, 1) OVER (PARTITION BY USER_ID ORDER BY START_TIME) AS END_TIME_PREVIOUS_VISIT 
		FROM RN

	)
SELECT USER_ID, TIMESTAMPDIFF(DAY, END_TIME_PREVIOUS_VISIT, START_TIME) AS DIFF_DAYS, 
TIMESTAMPDIFF(HOUR, END_TIME_PREVIOUS_VISIT, START_TIME) AS DIFF_HOURS
FROM END_TIME_PREVIOUS_VISIT 
WHERE RN = 1 
;